import * as moment from "moment";

export const skills = [
    { id: 1, name: ".NET", createdBy: "seed" },
    { id: 2, name: "Docker", createdBy: "seed" },
    { id: 3, name: "Visual Studio", createdBy: "seed" },
    { id: 4, name: "Python", createdBy: "seed" },
    { id: 5, name: "R Language", createdBy: "seed" },
    { id: 6, name: "RStudio", createdBy: "seed" },
    { id: 7, name: 'JavaScript', createdBy: 'seed' },
    { id: 8, name: 'React', createdBy: 'seed' },
    { id: 9, name: 'Node.js', createdBy: 'seed' },
    { id: 10, name: 'Angular', createdBy: 'seed' },
    { id: 11, name: 'Vue.js', createdBy: 'seed' },
    { id: 12, name: 'Swift', createdBy: 'seed' },
    { id: 13, name: 'Kotlin', createdBy: 'seed' },
    { id: 14, name: 'Java', createdBy: 'seed' },
    { id: 15, name: 'C#', createdBy: 'seed' },
    { id: 16, name: 'Ruby', createdBy: 'seed' },
    { id: 17, name: 'SQL', createdBy: 'seed' },
    { id: 18, name: 'NoSQL', createdBy: 'seed' },
    { id: 19, name: 'PHP', createdBy: 'seed' },
    { id: 20, name: 'HTML5', createdBy: 'seed' },
    { id: 21, name: 'CSS3', createdBy: 'seed' },
    { id: 22, name: 'TypeScript', createdBy: 'seed' },
    { id: 23, name: 'Go', createdBy: 'seed' },
    { id: 24, name: 'Rust', createdBy: 'seed' },
    { id: 25, name: 'C++', createdBy: 'seed' },
    { id: 26, name: 'Perl', createdBy: 'seed' },
    { id: 27, name: "Project Management", createdBy: "seed" },
    { id: 28, name: "Leadership", createdBy: "seed" },
    { id: 29, name: "Communication", createdBy: "seed" },
    { id: 30, name: "Teamwork", createdBy: "seed" },
    { id: 31, name: "Critical Thinking", createdBy: "seed" },
    { id: 32, name: "Problem Solving", createdBy: "seed" },
    { id: 33, name: "Time Management", createdBy: "seed" },
    { id: 34, name: "Creativity", createdBy: "seed" },
    { id: 35, name: "Data Analysis", createdBy: "seed" },
    { id: 36, name: "Machine Learning", createdBy: "seed" },
    { id: 37, name: "Artificial Intelligence", createdBy: "seed" },
    { id: 38, name: "Blockchain", createdBy: "seed" },
    { id: 39, name: "Cybersecurity", createdBy: "seed" },
    { id: 40, name: "Cloud Computing", createdBy: "seed" },
    { id: 41, name: "Digital Marketing", createdBy: "seed" },
    { id: 42, name: "SEO/SEM", createdBy: "seed" },
    { id: 43, name: "Social Media Management", createdBy: "seed" },
    { id: 44, name: "Graphic Design", createdBy: "seed" },
    { id: 45, name: "UI/UX Design", createdBy: "seed" },
    { id: 46, name: "Adobe Photoshop", createdBy: "seed" },
    { id: 47, name: "Adobe Illustrator", createdBy: "seed" },
    { id: 48, name: "Video Editing", createdBy: "seed" },
    { id: 49, name: "Animation", createdBy: "seed" },
    { id: 50, name: "3D Modeling", createdBy: "seed" },
    { id: 51, name: "Public Speaking", createdBy: "seed" },
    { id: 52, name: "Negotiation", createdBy: "seed" },
    { id: 53, name: "Sales", createdBy: "seed" },
    { id: 54, name: "Customer Service", createdBy: "seed" },
    { id: 55, name: "Human Resources", createdBy: "seed" },
    { id: 56, name: "Recruitment", createdBy: "seed" },
    { id: 57, name: "Event Planning", createdBy: "seed" },
    { id: 58, name: "Accounting", createdBy: "seed" },
    { id: 59, name: "Financial Analysis", createdBy: "seed" },
    { id: 60, name: "Risk Management", createdBy: "seed" },
    { id: 61, name: "Legal Compliance", createdBy: "seed" },
    { id: 62, name: "Supply Chain Management", createdBy: "seed" },
    { id: 63, name: "Logistics", createdBy: "seed" },
    { id: 64, name: "Foreign Languages", createdBy: "seed" },
    { id: 65, name: "Cultural Awareness", createdBy: "seed" },
    { id: 66, name: "Adaptability", createdBy: "seed" },
    { id: 67, name: "Emotional Intelligence", createdBy: "seed" },
    { id: 68, name: "Conflict Resolution", createdBy: "seed" },
    { id: 69, name: "Ethical Judgment", createdBy: "seed" },
    { id: 70, name: "Sustainability", createdBy: "seed" },
    { id: 71, name: "Renewable Energy", createdBy: "seed" },
    { id: 72, name: "Biotechnology", createdBy: "seed" },
    { id: 73, name: "Pharmaceuticals", createdBy: "seed" },
    { id: 74, name: "Clinical Research", createdBy: "seed" },
    { id: 75, name: "Genetics", createdBy: "seed" },
    { id: 76, name: "Epidemiology", createdBy: "seed" },
    { id: 77, name: "Public Health", createdBy: "seed" },
    { id: 78, name: "Nursing", createdBy: "seed" },
    { id: 79, name: "Physiotherapy", createdBy: "seed" },
    { id: 80, name: "Veterinary", createdBy: "seed" },
    { id: 81, name: "Agriculture", createdBy: "seed" },
    { id: 82, name: "Horticulture", createdBy: "seed" },
    { id: 83, name: "Environmental Science", createdBy: "seed" },
    { id: 84, name: "Geology", createdBy: "seed" },
    { id: 85, name: "Astronomy", createdBy: "seed" },
    { id: 86, name: "Physics", createdBy: "seed" },
    { id: 87, name: "Chemistry", createdBy: "seed" },
    { id: 88, name: "Mathematics", createdBy: "seed" },
    { id: 89, name: "Statistics", createdBy: "seed" },
    { id: 90, name: "Archaeology", createdBy: "seed" },
    { id: 91, name: "History", createdBy: "seed" },
    { id: 92, name: "Philosophy", createdBy: "seed" },
    { id: 93, name: "Literature", createdBy: "seed" },
    { id: 94, name: "Art History", createdBy: "seed" },
    { id: 95, name: "Music Theory", createdBy: "seed" },
    { id: 96, name: "Theatre Arts", createdBy: "seed" },
    { id: 97, name: "Dance", createdBy: "seed" },
    { id: 98, name: "Culinary Arts", createdBy: "seed" },
    { id: 99, name: "Hospitality", createdBy: "seed" },
    { id: 100, name: "Tourism", createdBy: "seed" },
    { id: 101, name: "Real Estate", createdBy: "seed" },
    { id: 102, name: "Urban Planning", createdBy: "seed" },
    { id: 103, name: "Construction", createdBy: "seed" },
    { id: 104, name: "Electrical Engineering", createdBy: "seed" },
    { id: 105, name: "Mechanical Engineering", createdBy: "seed" },
    { id: 106, name: "Civil Engineering", createdBy: "seed" },
    { id: 107, name: "Aerospace Engineering", createdBy: "seed" },
    { id: 108, name: "Biomedical Engineering", createdBy: "seed" },
    { id: 109, name: "Chemical Engineering", createdBy: "seed" },
    { id: 110, name: "Automotive", createdBy: "seed" },
    { id: 111, name: "Robotics", createdBy: "seed" },
    { id: 112, name: "Nanotechnology", createdBy: "seed" },
    { id: 113, name: "Material Science", createdBy: "seed" },
    { id: 114, name: "Fitness Training", createdBy: "seed" },
    { id: 115, name: "Yoga", createdBy: "seed" },
    { id: 116, name: "Meditation", createdBy: "seed" },
    { id: 117, name: "Nutrition", createdBy: "seed" },
    { id: 118, name: "Health and Wellness Coaching", createdBy: "seed" },
    { id: 119, name: "Personal Finance", createdBy: "seed" },
    { id: 120, name: "Investment Strategies", createdBy: "seed" },
    { id: 121, name: "Insurance", createdBy: "seed" },
    { id: 122, name: "Taxation", createdBy: "seed" },
    { id: 123, name: "E-commerce", createdBy: "seed" },
    { id: 124, name: "Retail Management", createdBy: "seed" },
    { id: 125, name: "Product Management", createdBy: "seed" },
    { id: 126, name: "Business Development", createdBy: "seed" }
]

export const positions = [
    { id: 1, name: "Deweloper .NET", description: "Deweloper backendu w .NET", createdBy: "seed" },
    { id: 2, name: "Analityk Danych - Python", description: "Analityk Danych korzystający z Pythona", createdBy: "seed" },
    { id: 3, name: 'Deweloper Frontendu', description: 'Deweloper specjalizujący się w technologiach frontendowych', createdBy: 'seed' },
    { id: 4, name: 'Deweloper Full Stack', description: 'Deweloper biegły zarówno w frontendzie jak i backendzie', createdBy: 'seed' },
    { id: 5, name: 'Deweloper Mobilny - Android', description: 'Deweloper aplikacji na Androida', createdBy: 'seed' },
    { id: 6, name: 'Deweloper Mobilny - iOS', description: 'Deweloper aplikacji na iOS', createdBy: 'seed' },
    { id: 7, name: 'Inżynier DevOps', description: 'Inżynier skupiający się na rozwoju i operacjach', createdBy: 'seed' },
    { id: 8, name: 'Inżynier Machine Learning', description: 'Specjalista od uczenia maszynowego i AI', createdBy: 'seed' },
    { id: 9, name: 'Data Scientist', description: 'Ekspert w analizie danych i modelowaniu', createdBy: 'seed' },
    { id: 10, name: 'Architekt Chmury', description: 'Projektant usług i architektury chmurowej', createdBy: 'seed' },
    { id: 11, name: 'Analityk Cyberbezpieczeństwa', description: 'Analityk skupiający się na aspektach bezpieczeństwa', createdBy: 'seed' },
    { id: 12, name: 'Administrator Baz Danych', description: 'Administrator systemów bazodanowych', createdBy: 'seed' },
    { id: 13, name: 'Analityk Systemów', description: 'Analityk systemów komputerowych i sieci', createdBy: 'seed' },
    { id: 14, name: 'Web Designer', description: 'Projektant specjalizujący się w interfejsach webowych', createdBy: 'seed' },
    { id: 15, name: 'Inżynier Zapewnienia Jakości', description: 'Inżynier dbający o jakość oprogramowania', createdBy: 'seed' },
    { id: 16, name: 'Kierownik Projektu', description: 'Menadżer projektów rozwoju oprogramowania', createdBy: 'seed' },
    { id: 17, name: 'Analityk Biznesowy', description: 'Analityk łączący potrzeby biznesowe i technologię', createdBy: 'seed' },
    { id: 18, name: 'Inżynier Sieciowy', description: 'Inżynier skupiający się na infrastrukturze sieciowej', createdBy: 'seed' },
    { id: 19, name: 'Technical Writer', description: 'Autor specjalizujący się w dokumentacji technicznej', createdBy: 'seed' },
    { id: 20, name: 'Projektant UX/UI', description: 'Projektant skupiający się na doświadczeniu i interfejsach użytkownika', createdBy: 'seed' },
    { id: 21, name: 'Deweloper Blockchain', description: 'Deweloper specjalizujący się w technologii blockchain', createdBy: 'seed' },
    { id: 22, name: 'Deweloper AR/VR', description: 'Deweloper aplikacji rozszerzonej i wirtualnej rzeczywistości', createdBy: 'seed' },
    { id: 23, name: 'Menadżer HR', description: 'Menadżer nadzorujący działalność HR', createdBy: 'seed' },
    { id: 24, name: 'Księgowy', description: 'Profesjonalista zajmujący się sprawami finansowymi', createdBy: 'seed' },
    { id: 25, name: 'Specjalista ds. Marketingu', description: 'Ekspert w strategiach i kampaniach marketingowych', createdBy: 'seed' },
    { id: 26, name: 'Przedstawiciel Handlowy', description: 'Profesjonalista odpowiedzialny za sprzedaż i relacje z klientami', createdBy: 'seed' },
    { id: 27, name: 'Przedstawiciel ds. Obsługi Klienta', description: 'Specjalista ds. relacji z klientami i wsparcia', createdBy: 'seed' },
    { id: 28, name: 'Asystent Administracyjny', description: 'Asystent zajmujący się zadaniami administracyjnymi', createdBy: 'seed' },
    { id: 29, name: 'Kierownik Operacyjny', description: 'Menadżer odpowiedzialny za nadzór nad operacjami', createdBy: 'seed' },
    { id: 30, name: 'Analityk Łańcucha Dostaw', description: 'Analityk skupiający się na zarządzaniu łańcuchem dostaw', createdBy: 'seed' },
    { id: 31, name: 'Menadżer Produktu', description: 'Menadżer odpowiedzialny za rozwój produktu i strategię', createdBy: 'seed' },
    { id: 32, name: 'Grafik', description: 'Projektant specjalizujący się w tworzeniu treści wizualnych', createdBy: 'seed' }
]

export const units = [
    { id: 1, name: 'Zarząd', parentId: null, createdBy: 'seed' },
    { id: 2, name: 'IT', parentId: 1, createdBy: 'seed' },
    { id: 3, name: 'Programiści', parentId: 2, createdBy: 'seed' },
    { id: 4, name: 'Administratorzy Systemów', parentId: 2, createdBy: 'seed' },
    { id: 5, name: 'Analitycy Danych', parentId: 2, createdBy: 'seed' },
    { id: 6, name: 'HR', parentId: 1, createdBy: 'seed' },
    { id: 7, name: 'Rekruterzy', parentId: 6, createdBy: 'seed' },
    { id: 8, name: 'Specjaliści ds. Szkoleń', parentId: 6, createdBy: 'seed' },
    { id: 9, name: 'Dział Finansowy', parentId: 1, createdBy: 'seed' },
    { id: 10, name: 'Księgowi', parentId: 9, createdBy: 'seed' },
    { id: 11, name: 'Analitycy Finansowi', parentId: 9, createdBy: 'seed' },
    { id: 12, name: 'Marketing', parentId: 1, createdBy: 'seed' },
    { id: 13, name: 'Specjaliści ds. Marketingu', parentId: 12, createdBy: 'seed' },
    { id: 14, name: 'Graficy', parentId: 12, createdBy: 'seed' }
]

export const users = [
    { id: 1, email: 'j.davis@test.com', firstname: 'John', lastname: 'Davis', description: 'Random user description', positionId: 5, unitId: 4, createdBy: 'seed' },
    { id: 2, email: 'jaskier@eh.com', firstname: 'Jaskier', lastname: 'Williams', description: 'Random user description', positionId: 4, unitId: 2, createdBy: 'seed', phone: '094393990' },
    { id: 3, email: 'j.garcia@test.com', firstname: 'John', lastname: 'Garcia', description: 'Random user description', positionId: 1, unitId: 3, createdBy: 'seed' },
    { id: 4, email: 'j.smith@test.com', firstname: 'James', lastname: 'Smith', description: 'Random user description', positionId: 2, unitId: 5, createdBy: 'seed' },
    { id: 5, email: 'l.davis@test.com', firstname: 'Laura', lastname: 'Davis', description: 'Random user description', positionId: 4, unitId: 2, createdBy: 'seed', phone: '641082406' },
    { id: 6, email: 'l.jones@test.com', firstname: 'Laura', lastname: 'Jones', description: 'Random user description', positionId: 5, unitId: 5, createdBy: 'seed', phone: '829315093' },
    { id: 7, email: 's.davis@test.com', firstname: 'Sarah', lastname: 'Davis', description: 'Random user description', positionId: 4, unitId: 2, createdBy: 'seed', phone: '812544578' },
    { id: 8, email: 'j.brown@test.com', firstname: 'James', lastname: 'Brown', description: 'Random user description', positionId: 3, unitId: 5, createdBy: 'seed', phone: '171717108' },
    { id: 9, email: 'm.garcia@test.com', firstname: 'Michael', lastname: 'Garcia', description: 'Random user description', positionId: 2, unitId: 4, createdBy: 'seed', phone: '840017653' },
    { id: 10, email: 'm.johnson@test.com', firstname: 'Michael', lastname: 'Johnson', description: 'Random user description', positionId: 3, unitId: 4, createdBy: 'seed', phone: '282861290' },
    { id: 11, email: 'e.wilson@test.com', firstname: 'Emily', lastname: 'Wilson', description: 'Random user description', positionId: 2, unitId: 1, createdBy: 'seed', phone: '773472193' },
    { id: 12, email: 'j.rodriguez@test.com', firstname: 'John', lastname: 'Rodriguez', description: 'Random user description', positionId: 5, unitId: 1, createdBy: 'seed' },
    { id: 13, email: 'j.johnson@test.com', firstname: 'Jane', lastname: 'Johnson', description: 'Random user description', positionId: 2, unitId: 3, createdBy: 'seed', phone: '296175808' },
    { id: 14, email: 'd.brown@test.com', firstname: 'David', lastname: 'Brown', description: 'Random user description', positionId: 2, unitId: 3, createdBy: 'seed', phone: '663528230' },
    { id: 15, email: 'd.rodriguez@test.com', firstname: 'David', lastname: 'Rodriguez', description: 'Random user description', positionId: 5, unitId: 4, createdBy: 'seed', phone: '636417760' },
    { id: 16, email: 'j.wilson@test.com', firstname: 'John', lastname: 'Wilson', description: 'Random user description', positionId: 1, unitId: 1, createdBy: 'seed' },
    { id: 17, email: 'd.smith@test.com', firstname: 'David', lastname: 'Smith', description: 'Random user description', positionId: 4, unitId: 4, createdBy: 'seed' },
    { id: 18, email: 'm.jones@test.com', firstname: 'Michael', lastname: 'Jones', description: 'Random user description', positionId: 1, unitId: 4, createdBy: 'seed' },
    { id: 19, email: 'l.rodriguez@test.com', firstname: 'Laura', lastname: 'Rodriguez', description: 'Random user description', positionId: 1, unitId: 2, createdBy: 'seed' },
    { id: 20, email: 'l.johnson@test.com', firstname: 'Laura', lastname: 'Johnson', description: 'Random user description', positionId: 3, unitId: 2, createdBy: 'seed' },
    { id: 21, email: 'j.williams@test.com', firstname: 'Jane', lastname: 'Williams', description: 'Random user description', positionId: 1, unitId: 3, createdBy: 'seed' },
    { id: 22, email: 'm.rodriguez@test.com', firstname: 'Michael', lastname: 'Rodriguez', description: 'Random user description', positionId: 4, unitId: 3, createdBy: 'seed', phone: '048076250' },
    { id: 23, email: 'a.davis@test.com', firstname: 'Alex', lastname: 'Davis', description: 'Random user description', positionId: 3, unitId: 2, createdBy: 'seed', phone: '856295023' },
    { id: 24, email: 'e.jones@test.com', firstname: 'Emily', lastname: 'Jones', description: 'Random user description', positionId: 1, unitId: 4, createdBy: 'seed', phone: '171890794' },
    { id: 25, email: 'm.brown@test.com', firstname: 'Michael', lastname: 'Brown', description: 'Random user description', positionId: 4, unitId: 4, createdBy: 'seed', phone: '448104808' },
    { id: 26, email: 'e.miller@test.com', firstname: 'Emily', lastname: 'Miller', description: 'Random user description', positionId: 1, unitId: 2, createdBy: 'seed' },
    { id: 27, email: 'e.davis@test.com', firstname: 'Emily', lastname: 'Davis', description: 'Random user description', positionId: 4, unitId: 5, createdBy: 'seed' },
    { id: 28, email: 'a.wilson@test.com', firstname: 'Alex', lastname: 'Wilson', description: 'Random user description', positionId: 5, unitId: 4, createdBy: 'seed', phone: '654204596' },
    { id: 29, email: 'a.smith@test.com', firstname: 'Alex', lastname: 'Smith', description: 'Random user description', positionId: 3, unitId: 1, createdBy: 'seed' },
    { id: 30, email: 'j.miller@test.com', firstname: 'Jane', lastname: 'Miller', description: 'Random user description', positionId: 5, unitId: 1, createdBy: 'seed', phone: '812337033' },
    { id: 31, email: 'd.garcia@test.com', firstname: 'David', lastname: 'Garcia', description: 'Random user description', positionId: 4, unitId: 4, createdBy: 'seed' },
    { id: 32, email: 'a.johnson@test.com', firstname: 'Alex', lastname: 'Johnson', description: 'Random user description', positionId: 5, unitId: 5, createdBy: 'seed', phone: '145219992' },
    { id: 33, email: 'm.smith@test.com', firstname: 'Michael', lastname: 'Smith', description: 'Random user description', positionId: 3, unitId: 2, createdBy: 'seed', phone: '059729495' },
    { id: 34, email: 'm.davis@test.com', firstname: 'Michael', lastname: 'Davis', description: 'Random user description', positionId: 4, unitId: 5, createdBy: 'seed' },
    { id: 35, email: 'a.williams@test.com', firstname: 'Alex', lastname: 'Williams', description: 'Random user description', positionId: 5, unitId: 1, createdBy: 'seed' },
    { id: 36, email: 'a.garcia@test.com', firstname: 'Anna', lastname: 'Garcia', description: 'Random user description', positionId: 1, unitId: 2, createdBy: 'seed', phone: '467732683' },
    { id: 37, email: 'a.brown@test.com', firstname: 'Alex', lastname: 'Brown', description: 'Random user description', positionId: 2, unitId: 1, createdBy: 'seed' },
    { id: 38, email: 'l.garcia@test.com', firstname: 'Laura', lastname: 'Garcia', description: 'Random user description', positionId: 2, unitId: 5, createdBy: 'seed', phone: '547388778' },
    { id: 39, email: 'm.miller@test.com', firstname: 'Michael', lastname: 'Miller', description: 'Random user description', positionId: 1, unitId: 5, createdBy: 'seed', phone: '222677338' },
    { id: 40, email: 'd.williams@test.com', firstname: 'David', lastname: 'Williams', description: 'Random user description', positionId: 4, unitId: 4, createdBy: 'seed', phone: '770787677' },
    { id: 41, email: 'j.violin@test.com', firstname: "John", lastname: "Violin", description: "I secretly really wanna be a painter", positionId: 1, phone: "111 111 111", createdBy: "seed", unitId: 2 },
    { id: 42, email: 'j.vengerberg@test.com', firstname: "Jenna", lastname: "Vengerberg", description: "Data Analyst", positionId: 2, unitId: 3, createdBy: "seed" }
]


export const experiences = [
    { id: 1, name: 'Software Developer at XYZ', description: 'Developing software using .NET and React', startDate: new Date('2021-01-11T13:50:02.339675'), endDate: new Date('2023-01-11T13:50:02.339690'), isPrivate: false, createdBy: 'seed', userId: 1 },
    { id: 2, name: 'Python Developer at ABC', description: 'Developing software using Python', startDate: new Date('2018-01-11T13:50:02.339694'), endDate: new Date('2020-01-11T13:50:02.339697'), isPrivate: false, createdBy: 'seed', userId: 2 },
    { id: 3, name: 'Data Analysts with R', description: 'Creating data statistics using R language', startDate: new Date('2020-01-11T13:50:02.339701'), endDate: new Date('2021-01-11T13:50:02.339704'), isPrivate: false, createdBy: 'seed', userId: 2 },
    { id: 4, name: 'Frontend Developer at DEF', description: 'Worked as a Frontend Developer', startDate: new Date('2020-01-11T13:50:02.340121'), endDate: new Date('2021-01-11T13:50:02.340169'), isPrivate: true, createdBy: 'seed', userId: 36 },
    { id: 5, name: 'Backend Developer at GHI', description: 'Worked as a Backend Developer', startDate: new Date('2023-01-11T13:50:02.340186'), endDate: new Date('2022-01-11T13:50:02.340191'), isPrivate: false, createdBy: 'seed', userId: 18 },
    { id: 6, name: 'Full Stack Developer at JKL', description: 'Worked as a Full Stack Developer', startDate: new Date('2017-01-11T13:50:02.340201'), endDate: new Date('2020-01-11T13:50:02.340206'), isPrivate: true, createdBy: 'seed', userId: 34 },
    { id: 7, name: 'DevOps Engineer at MNO', description: 'Worked as a DevOps Engineer', startDate: new Date('2022-01-11T13:50:02.340215'), endDate: new Date('2019-01-11T13:50:02.340219'), isPrivate: true, createdBy: 'seed', userId: 9 },
    { id: 8, name: 'UI/UX Designer at PQR', description: 'Worked as a UI/UX Designer', startDate: new Date('2022-01-11T13:50:02.340228'), endDate: new Date('2023-01-11T13:50:02.340233'), isPrivate: false, createdBy: 'seed', userId: 24 },
    { id: 9, name: 'Mobile Developer at STU', description: 'Worked as a Mobile Developer', startDate: new Date('2020-01-11T13:50:02.340243'), endDate: new Date('2020-01-11T13:50:02.340247'), isPrivate: false, createdBy: 'seed', userId: 25 },
    { id: 10, name: 'Project Manager at VWX', description: 'Worked as a Project Manager', startDate: new Date('2020-01-11T13:50:02.340262'), endDate: new Date('2019-01-11T13:50:02.340266'), isPrivate: false, createdBy: 'seed', userId: 7 },
    { id: 11, name: 'Product Owner at YZ', description: 'Worked as a Product Owner', startDate: new Date('2015-01-11T13:50:02.340274'), endDate: new Date('2024-01-11T13:50:02.340279'), isPrivate: false, createdBy: 'seed', userId: 11 },
    { id: 12, name: 'QA Engineer at ALPHA', description: 'Worked as a QA Engineer', startDate: new Date('2022-01-11T13:50:02.340297'), endDate: new Date('2019-01-11T13:50:02.340302'), isPrivate: true, createdBy: 'seed', userId: 41 },
    { id: 13, name: 'Business Analyst at BETA', description: 'Worked as a Business Analyst', startDate: new Date('2017-01-11T13:50:02.340312'), endDate: new Date('2022-01-11T13:50:02.340317'), isPrivate: true, createdBy: 'seed', userId: 16 },
    { id: 14, name: 'Cloud Engineer at GAMMA', description: 'Worked as a Cloud Engineer', startDate: new Date('2018-01-11T13:50:02.340327'), endDate: new Date('2022-01-11T13:50:02.340331'), isPrivate: true, createdBy: 'seed', userId: 40 },
    { id: 15, name: 'Data Scientist at DELTA', description: 'Worked as a Data Scientist', startDate: new Date('2021-01-11T13:50:02.340340'), endDate: new Date('2024-01-11T13:50:02.340344'), isPrivate: false, createdBy: 'seed', userId: 10 },
    { id: 16, name: 'Cybersecurity Specialist at EPSILON', description: 'Worked as a Cybersecurity Specialist', startDate: new Date('2018-01-11T13:50:02.340354'), endDate: new Date('2021-01-11T13:50:02.340359'), isPrivate: true, createdBy: 'seed', userId: 20 },
    { id: 17, name: 'Technical Writer at ZETA', description: 'Worked as a Technical Writer', startDate: new Date('2020-01-11T13:50:02.340393'), endDate: new Date('2023-01-11T13:50:02.340398'), isPrivate: true, createdBy: 'seed', userId: 12 },
    { id: 18, name: 'HR Specialist at ETA', description: 'Worked as a HR Specialist', startDate: new Date('2015-01-11T13:50:02.340482'), endDate: new Date('2020-01-11T13:50:02.340489'), isPrivate: true, createdBy: 'seed', userId: 29 },
    { id: 19, name: 'Marketing Manager at THETA', description: 'Worked as a Marketing Manager', startDate: new Date('2016-01-11T13:50:02.340497'), endDate: new Date('2020-01-11T13:50:02.340501'), isPrivate: true, createdBy: 'seed', userId: 42 },
    { id: 20, name: 'Sales Lead at IOTA', description: 'Worked as a Sales Lead', startDate: new Date('2021-01-11T13:50:02.340508'), endDate: new Date('2023-01-11T13:50:02.340512'), isPrivate: false, createdBy: 'seed', userId: 42 },
    { id: 21, name: 'Cybersecurity Specialist at EPSILON', description: 'Worked as a Product Owner', startDate: new Date('2018-01-11T13:52:26.241379'), endDate: new Date('2023-01-11T13:52:26.241411'), isPrivate: false, createdBy: 'seed', userId: 32 },
    { id: 22, name: 'QA Engineer at ALPHA', description: 'Worked as a Data Scientist', startDate: new Date('2014-01-11T13:52:26.241425'), endDate: new Date('2022-01-11T13:52:26.241431'), isPrivate: true, createdBy: 'seed', userId: 10 },
    { id: 23, name: 'Full Stack Developer at JKL', description: 'Worked as a Cybersecurity Specialist', startDate: new Date('2016-01-11T13:52:26.241444'), endDate: new Date('2024-01-11T13:52:26.241448'), isPrivate: false, createdBy: 'seed', userId: 22 },
    { id: 24, name: 'Backend Developer at GHI', description: 'Worked as a Marketing Manager', startDate: new Date('2017-01-11T13:52:26.241460'), endDate: new Date('2020-01-11T13:52:26.241464'), isPrivate: false, createdBy: 'seed', userId: 8 },
    { id: 25, name: 'Full Stack Developer at JKL', description: 'Worked as a Graphic Designer', startDate: new Date('2023-01-11T13:52:26.241475'), endDate: new Date('2022-01-11T13:52:26.241479'), isPrivate: true, createdBy: 'seed', userId: 10 },
    { id: 26, name: 'Project Manager at VWX', description: 'Worked as a Network Administrator', startDate: new Date('2023-01-11T13:52:26.241491'), endDate: new Date('2023-01-11T13:52:26.241495'), isPrivate: false, createdBy: 'seed', userId: 18 },
    { id: 27, name: 'Cloud Engineer at GAMMA', description: 'Worked as a Technical Writer', startDate: new Date('2019-01-11T13:52:26.241507'), endDate: new Date('2019-01-11T13:52:26.241512'), isPrivate: true, createdBy: 'seed', userId: 25 },
    { id: 28, name: 'Database Architect at MU', description: 'Worked as a Frontend Developer', startDate: new Date('2021-01-11T13:52:26.241522'), endDate: new Date('2021-01-11T13:52:26.241526'), isPrivate: true, createdBy: 'seed', userId: 13 },
    { id: 29, name: 'Data Scientist at DELTA', description: 'Worked as a Cybersecurity Specialist', startDate: new Date('2018-01-11T13:52:26.241537'), endDate: new Date('2019-01-11T13:52:26.241541'), isPrivate: true, createdBy: 'seed', userId: 5 },
    { id: 30, name: 'Database Architect at MU', description: 'Worked as a QA Engineer', startDate: new Date('2017-01-11T13:52:26.241551'), endDate: new Date('2019-01-11T13:52:26.241556'), isPrivate: true, createdBy: 'seed', userId: 9 },
    { id: 31, name: 'DevOps Engineer at MNO', description: 'Worked as a QA Engineer', startDate: new Date('2023-01-11T13:52:26.241569'), endDate: new Date('2022-01-11T13:52:26.241574'), isPrivate: false, createdBy: 'seed', userId: 30 },
    { id: 32, name: 'Cybersecurity Specialist at EPSILON', description: 'Worked as a Business Analyst', startDate: new Date('2014-01-11T13:52:26.241585'), endDate: new Date('2019-01-11T13:52:26.241589'), isPrivate: false, createdBy: 'seed', userId: 6 },
    { id: 33, name: 'Cloud Engineer at GAMMA', description: 'Worked as a Data Scientist', startDate: new Date('2023-01-11T13:52:26.241600'), endDate: new Date('2021-01-11T13:52:26.241606'), isPrivate: true, createdBy: 'seed', userId: 35 },
    { id: 34, name: 'Marketing Manager at THETA', description: 'Worked as a Backend Developer', startDate: new Date('2018-01-11T13:52:26.241616'), endDate: new Date('2021-01-11T13:52:26.241620'), isPrivate: false, createdBy: 'seed', userId: 3 },
    { id: 35, name: 'Technical Writer at ZETA', description: 'Worked as a DevOps Engineer', startDate: new Date('2020-01-11T13:52:26.241631'), endDate: new Date('2023-01-11T13:52:26.241636'), isPrivate: false, createdBy: 'seed', userId: 13 },
    { id: 36, name: 'Network Administrator at LAMBDA', description: 'Worked as a HR Specialist', startDate: new Date('2022-01-11T13:52:26.241648'), endDate: new Date('2020-01-11T13:52:26.241652'), isPrivate: false, createdBy: 'seed', userId: 42 },
    { id: 37, name: 'Project Manager at VWX', description: 'Worked as a Business Analyst', startDate: new Date('2014-01-11T13:52:26.241663'), endDate: new Date('2019-01-11T13:52:26.241668'), isPrivate: true, createdBy: 'seed', userId: 3 },
    { id: 38, name: 'Full Stack Developer at JKL', description: 'Worked as a Database Architect', startDate: new Date('2022-01-11T13:52:26.241678'), endDate: new Date('2021-01-11T13:52:26.241682'), isPrivate: false, createdBy: 'seed', userId: 27 },
    { id: 39, name: 'UI/UX Designer at PQR', description: 'Worked as a DevOps Engineer', startDate: new Date('2019-01-11T13:52:26.241692'), endDate: new Date('2024-01-11T13:52:26.241696'), isPrivate: true, createdBy: 'seed', userId: 20 },
    { id: 40, name: 'UI/UX Designer at PQR', description: 'Worked as a Technical Writer', startDate: new Date('2015-01-11T13:52:26.241708'), endDate: new Date('2022-01-11T13:52:26.241712'), isPrivate: true, createdBy: 'seed', userId: 4 },
    { id: 41, name: 'Technical Writer at ZETA', description: 'Worked as a Database Architect', startDate: new Date('2023-01-11T13:52:26.241722'), endDate: new Date('2021-01-11T13:52:26.241726'), isPrivate: false, createdBy: 'seed', userId: 31 },
    { id: 42, name: 'Cybersecurity Specialist at EPSILON', description: 'Worked as a Data Scientist', startDate: new Date('2023-01-11T13:52:26.241736'), endDate: new Date('2019-01-11T13:52:26.241740'), isPrivate: true, createdBy: 'seed', userId: 38 },
    { id: 43, name: 'Network Administrator at LAMBDA', description: 'Worked as a Full Stack Developer', startDate: new Date('2019-01-11T13:52:26.241751'), endDate: new Date('2023-01-11T13:52:26.241755'), isPrivate: false, createdBy: 'seed', userId: 6 },
    { id: 44, name: 'Project Manager at VWX', description: 'Worked as a Backend Developer', startDate: new Date('2023-01-11T13:52:26.241769'), endDate: new Date('2019-01-11T13:52:26.241774'), isPrivate: false, createdBy: 'seed', userId: 3 },
    { id: 45, name: 'Project Manager at VWX', description: 'Worked as a Data Scientist', startDate: new Date('2018-01-11T13:52:26.241784'), endDate: new Date('2024-01-11T13:52:26.241788'), isPrivate: false, createdBy: 'seed', userId: 27 },
    { id: 46, name: 'UI/UX Designer at PQR', description: 'Worked as a Data Scientist', startDate: new Date('2020-01-11T13:52:26.241800'), endDate: new Date('2024-01-11T13:52:26.241804'), isPrivate: false, createdBy: 'seed', userId: 35 },
    { id: 47, name: 'Backend Developer at GHI', description: 'Worked as a Mobile Developer', startDate: new Date('2017-01-11T13:52:26.242115'), endDate: new Date('2020-01-11T13:52:26.242129'), isPrivate: true, createdBy: 'seed', userId: 23 }
]

export const skillsOnUsers = [
    { skillId: 1, userId: 1, createdBy: "seed" },
    { skillId: 2, userId: 1, createdBy: "seed" },
    { skillId: 3, userId: 1, createdBy: "seed" },
    { skillId: 4, userId: 2, createdBy: "seed" },
    { skillId: 5, userId: 2, createdBy: "seed" },
    { skillId: 6, userId: 2, createdBy: "seed" },
    { skillId: 8, userId: 1, createdBy: "seed" },
    { skillId: 8, userId: 40, createdBy: "seed" },
    { skillId: 8, userId: 13, createdBy: "seed" },
    { skillId: 11, userId: 6, createdBy: "seed" },
    { skillId: 13, userId: 34, createdBy: "seed" },
    { skillId: 5, userId: 34, createdBy: "seed" },
    { skillId: 1, userId: 42, createdBy: "seed" },
    { skillId: 15, userId: 7, createdBy: "seed" },
    { skillId: 5, userId: 38, createdBy: "seed" },
    { skillId: 18, userId: 40, createdBy: "seed" },
    { skillId: 4, userId: 30, createdBy: "seed" },
    { skillId: 9, userId: 31, createdBy: "seed" },
    { skillId: 19, userId: 1, createdBy: "seed" },
    { skillId: 8, userId: 26, createdBy: "seed" },
    { skillId: 11, userId: 17, createdBy: "seed" },
    { skillId: 7, userId: 19, createdBy: "seed" },
    { skillId: 3, userId: 28, createdBy: "seed" },
    { skillId: 15, userId: 27, createdBy: "seed" },
    { skillId: 20, userId: 32, createdBy: "seed" },
    { skillId: 18, userId: 39, createdBy: "seed" },
    { skillId: 8, userId: 39, createdBy: "seed" },
    { skillId: 20, userId: 30, createdBy: "seed" },
    { skillId: 9, userId: 8, createdBy: "seed" },
    { skillId: 8, userId: 12, createdBy: "seed" },
    { skillId: 12, userId: 28, createdBy: "seed" },
    { skillId: 8, userId: 19, createdBy: "seed" },
    { skillId: 14, userId: 5, createdBy: "seed" },
    { skillId: 10, userId: 24, createdBy: "seed" },
    { skillId: 17, userId: 15, createdBy: "seed" },
    { skillId: 12, userId: 42, createdBy: "seed" },
    { skillId: 6, userId: 5, createdBy: "seed" },
    { skillId: 6, userId: 37, createdBy: "seed" },
    { skillId: 2, userId: 33, createdBy: "seed" },
    { skillId: 8, userId: 4, createdBy: "seed" },
    { skillId: 18, userId: 2, createdBy: "seed" },
    { skillId: 20, userId: 21, createdBy: "seed" },
    { skillId: 17, userId: 2, createdBy: "seed" },
    { skillId: 9, userId: 27, createdBy: "seed" },
    { skillId: 10, userId: 29, createdBy: "seed" },
    { skillId: 36, userId: 27, createdBy: "seed" },
    { skillId: 116, userId: 9, createdBy: "seed" },
    { skillId: 35, userId: 15, createdBy: "seed" },
    { skillId: 23, userId: 3, createdBy: "seed" },
    { skillId: 10, userId: 38, createdBy: "seed" },
    { skillId: 27, userId: 4, createdBy: "seed" },
    { skillId: 102, userId: 35, createdBy: "seed" },
    { skillId: 18, userId: 9, createdBy: "seed" },
    { skillId: 25, userId: 36, createdBy: "seed" },
    { skillId: 74, userId: 36, createdBy: "seed" },
    { skillId: 85, userId: 29, createdBy: "seed" },
    { skillId: 75, userId: 11, createdBy: "seed" },
    { skillId: 47, userId: 34, createdBy: "seed" },
    { skillId: 119, userId: 32, createdBy: "seed" },
    { skillId: 54, userId: 28, createdBy: "seed" },
    { skillId: 105, userId: 27, createdBy: "seed" },
    { skillId: 22, userId: 12, createdBy: "seed" },
    { skillId: 66, userId: 41, createdBy: "seed" },
    { skillId: 52, userId: 39, createdBy: "seed" },
    { skillId: 1, userId: 9, createdBy: "seed" },
    { skillId: 108, userId: 21, createdBy: "seed" },
    { skillId: 100, userId: 22, createdBy: "seed" },
    { skillId: 26, userId: 5, createdBy: "seed" },
    { skillId: 48, userId: 1, createdBy: "seed" },
    { skillId: 4, userId: 14, createdBy: "seed" },
    { skillId: 33, userId: 28, createdBy: "seed" },
    { skillId: 71, userId: 18, createdBy: "seed" },
    { skillId: 99, userId: 37, createdBy: "seed" },
    { skillId: 124, userId: 32, createdBy: "seed" },
    { skillId: 29, userId: 33, createdBy: "seed" },
    { skillId: 106, userId: 37, createdBy: "seed" },
    { skillId: 9, userId: 14, createdBy: "seed" },
    { skillId: 125, userId: 32, createdBy: "seed" },
    { skillId: 41, userId: 17, createdBy: "seed" },
    { skillId: 14, userId: 23, createdBy: "seed" },
    { skillId: 35, userId: 16, createdBy: "seed" },
    { skillId: 37, userId: 13, createdBy: "seed" },
    { skillId: 56, userId: 20, createdBy: "seed" },
    { skillId: 27, userId: 11, createdBy: "seed" },
    { skillId: 101, userId: 36, createdBy: "seed" },
    { skillId: 86, userId: 5, createdBy: "seed" },
    { skillId: 125, userId: 4, createdBy: "seed" },
    { skillId: 126, userId: 10, createdBy: "seed" },
    { skillId: 71, userId: 30, createdBy: "seed" },
    { skillId: 114, userId: 35, createdBy: "seed" },
    { skillId: 25, userId: 20, createdBy: "seed" },
    { skillId: 73, userId: 19, createdBy: "seed" },
    { skillId: 53, userId: 17, createdBy: "seed" },
    { skillId: 17, userId: 36, createdBy: "seed" },
    { skillId: 42, userId: 15, createdBy: "seed" },
    { skillId: 57, userId: 1, createdBy: "seed" },
    { skillId: 61, userId: 40, createdBy: "seed" },
    { skillId: 113, userId: 5, createdBy: "seed" },
    { skillId: 5, userId: 21, createdBy: "seed" },
    { skillId: 15, userId: 42, createdBy: "seed" },
    { skillId: 85, userId: 5, createdBy: "seed" },
    { skillId: 50, userId: 22, createdBy: "seed" },
    { skillId: 51, userId: 25, createdBy: "seed" },
    { skillId: 107, userId: 37, createdBy: "seed" },
    { skillId: 53, userId: 7, createdBy: "seed" },
    { skillId: 107, userId: 34, createdBy: "seed" },
    { skillId: 25, userId: 16, createdBy: "seed" },
    { skillId: 126, userId: 15, createdBy: "seed" },
    { skillId: 95, userId: 26, createdBy: "seed" },
    { skillId: 81, userId: 37, createdBy: "seed" },
    { skillId: 90, userId: 40, createdBy: "seed" },
    { skillId: 86, userId: 13, createdBy: "seed" },
    { skillId: 34, userId: 11, createdBy: "seed" },
    { skillId: 16, userId: 21, createdBy: "seed" },
    { skillId: 106, userId: 23, createdBy: "seed" },
    { skillId: 14, userId: 35, createdBy: "seed" },
    { skillId: 14, userId: 30, createdBy: "seed" },
    { skillId: 34, userId: 27, createdBy: "seed" },
    { skillId: 60, userId: 42, createdBy: "seed" },
    { skillId: 14, userId: 25, createdBy: "seed" },
    { skillId: 104, userId: 17, createdBy: "seed" },
    { skillId: 33, userId: 3, createdBy: "seed" },
    { skillId: 6, userId: 12, createdBy: "seed" },
    { skillId: 5, userId: 23, createdBy: "seed" },
    { skillId: 54, userId: 3, createdBy: "seed" },
    { skillId: 28, userId: 38, createdBy: "seed" },
    { skillId: 113, userId: 22, createdBy: "seed" },
    { skillId: 80, userId: 21, createdBy: "seed" },
    { skillId: 5, userId: 17, createdBy: "seed" },
    { skillId: 92, userId: 24, createdBy: "seed" },
    { skillId: 69, userId: 14, createdBy: "seed" },
    { skillId: 78, userId: 4, createdBy: "seed" },
    { skillId: 30, userId: 20, createdBy: "seed" },
    { skillId: 115, userId: 38, createdBy: "seed" },
    { skillId: 55, userId: 19, createdBy: "seed" },
    { skillId: 96, userId: 18, createdBy: "seed" },
    { skillId: 59, userId: 10, createdBy: "seed" },
    { skillId: 24, userId: 39, createdBy: "seed" },
    { skillId: 63, userId: 30, createdBy: "seed" },
    { skillId: 109, userId: 21, createdBy: "seed" },
    { skillId: 42, userId: 28, createdBy: "seed" },
    { skillId: 80, userId: 37, createdBy: "seed" },
    { skillId: 74, userId: 15, createdBy: "seed" },
    { skillId: 5, userId: 14, createdBy: "seed" },
    { skillId: 29, userId: 37, createdBy: "seed" },
    { skillId: 9, userId: 38, createdBy: "seed" },
    { skillId: 91, userId: 6, createdBy: "seed" },
    { skillId: 72, userId: 30, createdBy: "seed" },
    { skillId: 114, userId: 24, createdBy: "seed" },
    { skillId: 81, userId: 39, createdBy: "seed" },
    { skillId: 4, userId: 38, createdBy: "seed" },
    { skillId: 77, userId: 39, createdBy: "seed" },
    { skillId: 82, userId: 14, createdBy: "seed" },
    { skillId: 36, userId: 25, createdBy: "seed" },
    { skillId: 80, userId: 14, createdBy: "seed" },
    { skillId: 52, userId: 21, createdBy: "seed" },
    { skillId: 121, userId: 22, createdBy: "seed" },
    { skillId: 17, userId: 40, createdBy: "seed" },
    { skillId: 85, userId: 16, createdBy: "seed" },
    { skillId: 113, userId: 4, createdBy: "seed" },
    { skillId: 88, userId: 3, createdBy: "seed" },
    { skillId: 46, userId: 30, createdBy: "seed" },
    { skillId: 79, userId: 27, createdBy: "seed" },
    { skillId: 124, userId: 1, createdBy: "seed" },
    { skillId: 10, userId: 3, createdBy: "seed" },
    { skillId: 81, userId: 14, createdBy: "seed" },
    { skillId: 53, userId: 6, createdBy: "seed" },
    { skillId: 82, userId: 3, createdBy: "seed" },
    { skillId: 114, userId: 40, createdBy: "seed" },
    { skillId: 123, userId: 21, createdBy: "seed" },
    { skillId: 111, userId: 3, createdBy: "seed" },
    { skillId: 20, userId: 35, createdBy: "seed" },
    { skillId: 99, userId: 7, createdBy: "seed" },
    { skillId: 83, userId: 19, createdBy: "seed" },
    { skillId: 108, userId: 27, createdBy: "seed" },
    { skillId: 19, userId: 19, createdBy: "seed" },
    { skillId: 83, userId: 39, createdBy: "seed" },
    { skillId: 106, userId: 21, createdBy: "seed" },
    { skillId: 91, userId: 41, createdBy: "seed" },
    { skillId: 108, userId: 32, createdBy: "seed" },
    { skillId: 39, userId: 14, createdBy: "seed" },
    { skillId: 113, userId: 41, createdBy: "seed" },
    { skillId: 75, userId: 31, createdBy: "seed" },
    { skillId: 120, userId: 18, createdBy: "seed" },
    { skillId: 23, userId: 15, createdBy: "seed" },
    { skillId: 77, userId: 4, createdBy: "seed" },
    { skillId: 68, userId: 22, createdBy: "seed" },
    { skillId: 71, userId: 32, createdBy: "seed" },
    { skillId: 49, userId: 42, createdBy: "seed" },
    { skillId: 109, userId: 8, createdBy: "seed" },
    { skillId: 78, userId: 3, createdBy: "seed" },
    { skillId: 11, userId: 14, createdBy: "seed" },
    { skillId: 100, userId: 28, createdBy: "seed" },
    { skillId: 4, userId: 13, createdBy: "seed" },
    { skillId: 99, userId: 2, createdBy: "seed" },
    { skillId: 122, userId: 20, createdBy: "seed" },
    { skillId: 21, userId: 37, createdBy: "seed" },
    { skillId: 122, userId: 23, createdBy: "seed" },
    { skillId: 84, userId: 5, createdBy: "seed" },
    { skillId: 45, userId: 12, createdBy: "seed" },
    { skillId: 49, userId: 38, createdBy: "seed" },
    { skillId: 10, userId: 35, createdBy: "seed" },
    { skillId: 82, userId: 20, createdBy: "seed" },
    { skillId: 56, userId: 31, createdBy: "seed" },
    { skillId: 11, userId: 23, createdBy: "seed" },
    { skillId: 101, userId: 34, createdBy: "seed" },
    { skillId: 18, userId: 37, createdBy: "seed" },
    { skillId: 44, userId: 38, createdBy: "seed" },
    { skillId: 17, userId: 25, createdBy: "seed" },
    { skillId: 108, userId: 11, createdBy: "seed" },
    { skillId: 84, userId: 17, createdBy: "seed" },
    { skillId: 94, userId: 8, createdBy: "seed" },
    { skillId: 113, userId: 35, createdBy: "seed" },
    { skillId: 67, userId: 9, createdBy: "seed" },
    { skillId: 52, userId: 33, createdBy: "seed" },
    { skillId: 92, userId: 26, createdBy: "seed" },
    { skillId: 100, userId: 4, createdBy: "seed" },
    { skillId: 13, userId: 5, createdBy: "seed" },
    { skillId: 25, userId: 5, createdBy: "seed" },
    { skillId: 2, userId: 8, createdBy: "seed" },
    { skillId: 105, userId: 36, createdBy: "seed" },
    { skillId: 77, userId: 33, createdBy: "seed" },
    { skillId: 96, userId: 9, createdBy: "seed" },
    { skillId: 75, userId: 14, createdBy: "seed" },
    { skillId: 68, userId: 32, createdBy: "seed" },
    { skillId: 87, userId: 28, createdBy: "seed" },
    { skillId: 31, userId: 25, createdBy: "seed" },
    { skillId: 112, userId: 11, createdBy: "seed" },
    { skillId: 40, userId: 7, createdBy: "seed" },
    { skillId: 87, userId: 7, createdBy: "seed" },
    { skillId: 86, userId: 9, createdBy: "seed" },
    { skillId: 60, userId: 2, createdBy: "seed" },
    { skillId: 119, userId: 27, createdBy: "seed" },
    { skillId: 41, userId: 29, createdBy: "seed" },
    { skillId: 78, userId: 18, createdBy: "seed" },
    { skillId: 82, userId: 2, createdBy: "seed" },
    { skillId: 124, userId: 23, createdBy: "seed" },
    { skillId: 106, userId: 19, createdBy: "seed" },
    { skillId: 99, userId: 42, createdBy: "seed" },
    { skillId: 121, userId: 13, createdBy: "seed" },
    { skillId: 64, userId: 28, createdBy: "seed" },
    { skillId: 57, userId: 26, createdBy: "seed" },
    { skillId: 90, userId: 41, createdBy: "seed" },
    { skillId: 5, userId: 36, createdBy: "seed" },
    { skillId: 88, userId: 25, createdBy: "seed" },
    { skillId: 30, userId: 10, createdBy: "seed" },
    { skillId: 82, userId: 34, createdBy: "seed" },
    { skillId: 52, userId: 13, createdBy: "seed" },
    { skillId: 66, userId: 2, createdBy: "seed" },
    { skillId: 122, userId: 35, createdBy: "seed" },
    { skillId: 16, userId: 26, createdBy: "seed" },
    { skillId: 3, userId: 38, createdBy: "seed" },
    { skillId: 96, userId: 33, createdBy: "seed" },
    { skillId: 24, userId: 14, createdBy: "seed" },
    { skillId: 108, userId: 37, createdBy: "seed" },
    { skillId: 68, userId: 13, createdBy: "seed" },
    { skillId: 79, userId: 42, createdBy: "seed" },
    { skillId: 83, userId: 13, createdBy: "seed" },
    { skillId: 53, userId: 28, createdBy: "seed" },
    { skillId: 20, userId: 1, createdBy: "seed" },
    { skillId: 90, userId: 9, createdBy: "seed" },
    { skillId: 56, userId: 5, createdBy: "seed" },
    { skillId: 36, userId: 17, createdBy: "seed" },
    { skillId: 77, userId: 21, createdBy: "seed" },
    { skillId: 33, userId: 2, createdBy: "seed" },
    { skillId: 34, userId: 32, createdBy: "seed" },
    { skillId: 84, userId: 1, createdBy: "seed" },
    { skillId: 85, userId: 13, createdBy: "seed" },
    { skillId: 112, userId: 40, createdBy: "seed" },
    { skillId: 93, userId: 18, createdBy: "seed" },
    { skillId: 50, userId: 27, createdBy: "seed" },
    { skillId: 117, userId: 18, createdBy: "seed" },
    { skillId: 47, userId: 26, createdBy: "seed" },
    { skillId: 24, userId: 13, createdBy: "seed" },
    { skillId: 55, userId: 13, createdBy: "seed" },
    { skillId: 57, userId: 30, createdBy: "seed" },
    { skillId: 86, userId: 28, createdBy: "seed" },
    { skillId: 40, userId: 33, createdBy: "seed" },
    { skillId: 58, userId: 39, createdBy: "seed" },
    { skillId: 119, userId: 40, createdBy: "seed" },
    { skillId: 27, userId: 27, createdBy: "seed" },
    { skillId: 52, userId: 38, createdBy: "seed" },
    { skillId: 119, userId: 7, createdBy: "seed" },
    { skillId: 19, userId: 11, createdBy: "seed" },
    { skillId: 89, userId: 3, createdBy: "seed" },
    { skillId: 88, userId: 13, createdBy: "seed" },
    { skillId: 80, userId: 23, createdBy: "seed" },
    { skillId: 71, userId: 33, createdBy: "seed" },
    { skillId: 7, userId: 16, createdBy: "seed" },
    { skillId: 18, userId: 1, createdBy: "seed" },
    { skillId: 52, userId: 24, createdBy: "seed" },
    { skillId: 60, userId: 3, createdBy: "seed" },
    { skillId: 12, userId: 35, createdBy: "seed" },
    { skillId: 109, userId: 23, createdBy: "seed" },
    { skillId: 109, userId: 41, createdBy: "seed" },
    { skillId: 24, userId: 16, createdBy: "seed" },
    { skillId: 12, userId: 20, createdBy: "seed" },
    { skillId: 119, userId: 35, createdBy: "seed" },
    { skillId: 110, userId: 1, createdBy: "seed" },
    { skillId: 5, userId: 26, createdBy: "seed" },
    { skillId: 104, userId: 40, createdBy: "seed" },
    { skillId: 125, userId: 7, createdBy: "seed" },
    { skillId: 67, userId: 1, createdBy: "seed" },
    { skillId: 63, userId: 17, createdBy: "seed" },
    { skillId: 41, userId: 5, createdBy: "seed" },
    { skillId: 17, userId: 29, createdBy: "seed" },
    { skillId: 74, userId: 29, createdBy: "seed" },
    { skillId: 114, userId: 30, createdBy: "seed" },
    { skillId: 104, userId: 41, createdBy: "seed" },
    { skillId: 64, userId: 21, createdBy: "seed" },
    { skillId: 76, userId: 5, createdBy: "seed" },
    { skillId: 84, userId: 28, createdBy: "seed" },
    { skillId: 98, userId: 6, createdBy: "seed" },
    { skillId: 122, userId: 38, createdBy: "seed" },
    { skillId: 85, userId: 8, createdBy: "seed" },
    { skillId: 94, userId: 4, createdBy: "seed" },
    { skillId: 6, userId: 41, createdBy: "seed" },
    { skillId: 123, userId: 30, createdBy: "seed" },
    { skillId: 100, userId: 39, createdBy: "seed" },
    { skillId: 83, userId: 24, createdBy: "seed" },
    { skillId: 12, userId: 25, createdBy: "seed" },
    { skillId: 38, userId: 21, createdBy: "seed" },
    { skillId: 94, userId: 29, createdBy: "seed" },
    { skillId: 50, userId: 15, createdBy: "seed" },
    { skillId: 69, userId: 8, createdBy: "seed" },
    { skillId: 65, userId: 13, createdBy: "seed" },
    { skillId: 17, userId: 30, createdBy: "seed" },
    { skillId: 56, userId: 17, createdBy: "seed" },
    { skillId: 72, userId: 32, createdBy: "seed" },
    { skillId: 123, userId: 2, createdBy: "seed" },
    { skillId: 69, userId: 39, createdBy: "seed" },
    { skillId: 110, userId: 24, createdBy: "seed" },
    { skillId: 95, userId: 38, createdBy: "seed" },
    { skillId: 68, userId: 27, createdBy: "seed" },
    { skillId: 85, userId: 41, createdBy: "seed" },
    { skillId: 77, userId: 1, createdBy: "seed" },
    { skillId: 103, userId: 16, createdBy: "seed" },
    { skillId: 45, userId: 8, createdBy: "seed" },
    { skillId: 124, userId: 28, createdBy: "seed" },
    { skillId: 88, userId: 29, createdBy: "seed" },
    { skillId: 37, userId: 38, createdBy: "seed" },
    { skillId: 99, userId: 11, createdBy: "seed" },
    { skillId: 103, userId: 22, createdBy: "seed" },
    { skillId: 74, userId: 1, createdBy: "seed" },
    { skillId: 57, userId: 13, createdBy: "seed" },
];